name: "PreTeXt Build"
description: "Builds a project with PreTeXt"
inputs:
    project-root:
        description: "The root directory of the project. I.e., the folder where your `project.ptx` is located."
        required: false
        default: "."
runs:
    using: "docker"
    image: Dockerfile
    args:
        - ${{ inputs.project-root }}
