name: "PreTeXt Build"
description: "Builds a project with PreTeXt"
inputs:
    project-root:
        description: "The root directory of the project. I.e., the folder where your `project.ptx` is located."
        required: false
        default: "."
    pretext-command:
        description: "The command to run to build the project. For example `build html` would execute `pretext build html`."
        required: false
        default: "build"
    output-dir:
        description: "The directory where the generated output should be placed."
        required: false
        default: "output"
runs:
    using: "docker"
    image: Dockerfile
    args:
        - ${{ inputs.project-root }}
