name: Test Action

on:
    push:
        branches: ["master", "main"]
    pull_request:
        branches: ["master", "main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Action
              uses: actions/checkout@v4
              with:
                  path: action

            - name: Checkout PreTeXt examples
              uses: actions/checkout@v4
              with:
                  repository: "PreTeXtBook/pretext"
                  path: pretext

            - name: Run action on examples/minimal
              # uses: siefkenj/pretext-build-action@main
              uses: ./action
              with:
                  project-root: "pretext/examples/minimal"
                  output-dir: out/out1

            - name: Run action with custom pretext/pretext path
              # uses: siefkenj/pretext-build-action@main
              uses: ./action
              with:
                  project-root: "pretext/examples/minimal"
                  pretext-commit: 94175d7
                  output-dir: out/out2
            
            - name: Run action with custom pretext/pretext commit
              # uses: siefkenj/pretext-build-action@main
              uses: ./action
              with:
                  project-root: "pretext/examples/minimal"
                  pretext-commit: 94175d7
                  output-dir: out/out3

            # Save the output of out/ as an artifact
            - name: Archive output
              uses: actions/upload-artifact@v4
              with:
                  name: output
                  path: out/
