name: Test Action

on:
    push:
        branches: ["master", "main"]
    pull_request:
        branches: ["master", "main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Action
              uses: actions/checkout@v4
            
            - name: Checkout PreTeXt examples
              uses: actions/checkout@v4
              with:
                  repository: "PreTeXtBook/pretext"

            - name: Echo
              run: |
                ls -a
                echo "Hello, World!"

            - name: Run action
              # uses: siefkenj/pretext-build-action@main
              uses: ./
              with:
                  project-root: "examples/minimal"
